/**
 * MCM Research Agent
 *
 * A research agent that gathers data on Mid-Century Modern architects and homes.
 * Can be run manually or scheduled as a daily cron job.
 *
 * Usage:
 *   npx tsx scripts/research-agent.ts daily          # Run daily scan
 *   npx tsx scripts/research-agent.ts architect "Bruce Goff"
 *   npx tsx scripts/research-agent.ts property "Chemosphere"
 *   npx tsx scripts/research-agent.ts listings
 */

import * as fs from 'fs'
import * as path from 'path'

const DATA_DIR = path.join(__dirname, '../src/data')
const REPORTS_DIR = path.join(__dirname, '../reports')

interface Property {
  id: string
  slug: string
  home_name: string
  architect_id: string
  last_sale_price: number | null
  status: string
  [key: string]: unknown
}

interface Architect {
  id: string
  slug: string
  name: string
  [key: string]: unknown
}

// Ensure reports directory exists
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true })
}

// Load current data
function loadProperties(): Property[] {
  const data = fs.readFileSync(path.join(DATA_DIR, 'properties.json'), 'utf-8')
  return JSON.parse(data)
}

function loadArchitects(): Architect[] {
  const data = fs.readFileSync(path.join(DATA_DIR, 'architects.json'), 'utf-8')
  return JSON.parse(data)
}

// Search queries for finding MCM listings
const SEARCH_QUERIES = [
  'John Lautner house for sale',
  'E. Fay Jones house for sale',
  'Alden B. Dow house for sale',
  'mid century modern architect designed home for sale',
  'Frank Lloyd Wright apprentice house listing',
  'Taliesin architect home for sale',
  'organic architecture home for sale',
  'usonian home for sale',
]

// Architects to track for new listings
const TRACKED_ARCHITECTS = [
  'John Lautner',
  'E. Fay Jones',
  'Alden B. Dow',
  'Paolo Soleri',
  'Aaron Green',
  'Edgar Tafel',
  'Arthur Dyson',
  'Eric Lloyd Wright',
  'Cornelia Brierly',
  'William Wesley Peters',
  'John Rattenbury',
  'Vernon Swaback',
]

// Generate daily report template
function generateDailyReport(): string {
  const properties = loadProperties()
  const architects = loadArchitects()
  const date = new Date().toISOString().split('T')[0]

  const report = `# Usonian Daily Research Report - ${date}

## Current Database Status
- **Properties**: ${properties.length}
- **Architects**: ${architects.length}

## Properties by Status
${getStatusSummary(properties)}

## Search Queries to Run
${SEARCH_QUERIES.map((q, i) => `${i + 1}. "${q}"`).join('\n')}

## Architects to Monitor
${TRACKED_ARCHITECTS.map(a => `- ${a}`).join('\n')}

## Research Tasks

### 1. Check Existing Listings
Review these properties for status changes:
${properties
  .filter(p => p.status === 'active' || p.last_sale_price)
  .slice(0, 10)
  .map(p => `- [ ] ${p.home_name} (${p.architect_id})`)
  .join('\n')}

### 2. Search for New Listings
Run the search queries above and document any new findings.

### 3. Verify Recent Sales
Check county records for properties marked as recently sold.

## Notes
_Add research notes here_

---
Generated by MCM Research Agent
`

  return report
}

function getStatusSummary(properties: Property[]): string {
  const counts: Record<string, number> = {}
  for (const p of properties) {
    counts[p.status] = (counts[p.status] || 0) + 1
  }
  return Object.entries(counts)
    .map(([status, count]) => `- ${status}: ${count}`)
    .join('\n')
}

// Generate architect research template
function generateArchitectTemplate(name: string): string {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

  return `# Architect Research: ${name}

## Basic Information
- **Full Name**: ${name}
- **Slug**: ${slug}
- **Birth Year**:
- **Death Year**:
- **Birthplace**:

## FLW/Taliesin Connection
- **Fellowship Years**:
- **Role at Taliesin**:
- **Notable Projects with FLW**:

## Biography
_Write 2-3 sentences about their career and significance_

## Notable Works
1.
2.
3.

## Sources
- [ ] Wikipedia
- [ ] FLW Foundation
- [ ] AIA records
- [ ] University archives

## JSON Output
\`\`\`json
{
  "id": "${slug}",
  "slug": "${slug}",
  "name": "${name}",
  "birth_year": null,
  "death_year": null,
  "birthplace": null,
  "biography": "",
  "fellowship_years": null,
  "image_url": null,
  "property_count": 0
}
\`\`\`

---
Generated by MCM Research Agent
`
}

// Generate property research template
function generatePropertyTemplate(name: string): string {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

  return `# Property Research: ${name}

## Basic Information
- **Home Name**: ${name}
- **Slug**: ${slug}
- **Full Address**:
- **City**:
- **State**:
- **Year Built**:

## Architect
- **Architect Name**:
- **Architect ID**:

## Ownership
- **Original Owner/Client**:
- **Current Owner**:

## Property Details
- **Square Footage**:
- **Bedrooms**:
- **Bathrooms**:

## Preservation Status
- [ ] NRHP (National Register of Historic Places)
- [ ] NHL (National Historic Landmark)
- [ ] State Register
- [ ] Local Landmark
- [ ] None

## Sales History
| Date | Price | Buyer | Notes |
|------|-------|-------|-------|
|      |       |       |       |

## Description
_Architectural description and significance_

## Images
- Best Image URL:

## Sources
- [ ] Zillow/Redfin
- [ ] County records
- [ ] Preservation database
- [ ] Architectural publications

## JSON Output
\`\`\`json
{
  "id": "${slug}",
  "slug": "${slug}",
  "home_name": "${name}",
  "full_address": null,
  "parsed_city": null,
  "parsed_state": null,
  "country": "USA",
  "latitude": null,
  "longitude": null,
  "year_built": null,
  "architect_id": "",
  "client_owner": null,
  "current_owner": null,
  "preservation_status": null,
  "significance": null,
  "description": null,
  "curator_notes": null,
  "square_footage": null,
  "bedrooms": null,
  "bathrooms": null,
  "status": "archived",
  "best_image_url": null,
  "last_sale_price": null,
  "last_sale_date": null,
  "created_at": "${new Date().toISOString().split('T')[0]}",
  "updated_at": "${new Date().toISOString().split('T')[0]}"
}
\`\`\`

---
Generated by MCM Research Agent
`
}

// Generate listings search template
function generateListingsTemplate(): string {
  const architects = loadArchitects()

  return `# MCM Listings Research

## Search Queries

### General MCM Searches
${SEARCH_QUERIES.map((q, i) => `${i + 1}. [${q}](https://www.google.com/search?q=${encodeURIComponent(q)})`).join('\n')}

### Architect-Specific Searches
${architects.slice(0, 15).map(a =>
  `- [${a.name} house for sale](https://www.google.com/search?q=${encodeURIComponent(a.name + ' house for sale')})`
).join('\n')}

## Real Estate Sites to Check
- [Zillow MCM](https://www.zillow.com/)
- [Redfin](https://www.redfin.com/)
- [Sotheby's](https://www.sothebysrealty.com/)
- [Christie's Real Estate](https://www.christiesrealestate.com/)
- [Dwell](https://www.dwell.com/homes-for-sale)

## New Listings Found

### Listing 1
- **Property Name**:
- **Architect**:
- **Location**:
- **Year Built**:
- **Asking Price**:
- **Listing URL**:
- **Status**: New / Price Change / Back on Market

### Listing 2
_Copy template above_

## Price Changes

| Property | Old Price | New Price | Change |
|----------|-----------|-----------|--------|
|          |           |           |        |

## Sold Properties

| Property | Sale Price | Sale Date | Buyer |
|----------|------------|-----------|-------|
|          |            |           |       |

---
Generated by MCM Research Agent
`
}

// Main CLI
async function main() {
  const args = process.argv.slice(2)
  const command = args[0] || 'help'
  const param = args.slice(1).join(' ')

  const date = new Date().toISOString().split('T')[0]

  switch (command) {
    case 'daily': {
      const report = generateDailyReport()
      const filename = `daily-report-${date}.md`
      fs.writeFileSync(path.join(REPORTS_DIR, filename), report)
      console.log(`Daily report generated: reports/${filename}`)
      console.log(report)
      break
    }

    case 'architect': {
      if (!param) {
        console.error('Usage: npx tsx scripts/research-agent.ts architect "Architect Name"')
        process.exit(1)
      }
      const template = generateArchitectTemplate(param)
      const slug = param.toLowerCase().replace(/[^a-z0-9]+/g, '-')
      const filename = `architect-${slug}-${date}.md`
      fs.writeFileSync(path.join(REPORTS_DIR, filename), template)
      console.log(`Architect research template generated: reports/${filename}`)
      console.log(template)
      break
    }

    case 'property': {
      if (!param) {
        console.error('Usage: npx tsx scripts/research-agent.ts property "Property Name"')
        process.exit(1)
      }
      const template = generatePropertyTemplate(param)
      const slug = param.toLowerCase().replace(/[^a-z0-9]+/g, '-')
      const filename = `property-${slug}-${date}.md`
      fs.writeFileSync(path.join(REPORTS_DIR, filename), template)
      console.log(`Property research template generated: reports/${filename}`)
      console.log(template)
      break
    }

    case 'listings': {
      const template = generateListingsTemplate()
      const filename = `listings-${date}.md`
      fs.writeFileSync(path.join(REPORTS_DIR, filename), template)
      console.log(`Listings research template generated: reports/${filename}`)
      console.log(template)
      break
    }

    case 'help':
    default:
      console.log(`
MCM Research Agent

Usage:
  npx tsx scripts/research-agent.ts <command> [options]

Commands:
  daily                      Generate daily research report
  architect "<name>"         Generate architect research template
  property "<name>"          Generate property research template
  listings                   Generate listings search template
  help                       Show this help message

Examples:
  npx tsx scripts/research-agent.ts daily
  npx tsx scripts/research-agent.ts architect "Bruce Goff"
  npx tsx scripts/research-agent.ts property "Chemosphere"
  npx tsx scripts/research-agent.ts listings

Reports are saved to: ./reports/
`)
  }
}

main().catch(console.error)
